"""
Test proteins discovered from batch analysis
Auto-generated by expand_test_suite_now.py
"""

# Proteins discovered from actual batch content
BATCH_TEST_PROTEINS = {
    "8ovp_A": {
        "category": "validated",
        "description": "GFP-PBP fusion - validated test case",
        "estimated_length": 569,
        "estimated_domains": 3,
        "evidence_total": 3,
        "chain_blast": 1,
        "domain_blast": 1,
        "hhsearch": 1,
        "tgroups": ['5025.1.1', '7579.1.1']
    },
    "8oni_L": {
        "category": "chain_blast_multi",
        "description": "Multi-domain with chain BLAST (2945 domains)",
        "estimated_length": 213,
        "estimated_domains": 2945,
        "evidence_total": 10869,
        "chain_blast": 5000,
        "domain_blast": 5000,
        "hhsearch": 869,
        "tgroups": []
    },
    "8p6i_L": {
        "category": "chain_blast_multi",
        "description": "Multi-domain with chain BLAST (2720 domains)",
        "estimated_length": 220,
        "estimated_domains": 2720,
        "evidence_total": 10859,
        "chain_blast": 5000,
        "domain_blast": 5000,
        "hhsearch": 859,
        "tgroups": []
    },
    "8p2e_B": {
        "category": "chain_blast_multi",
        "description": "Multi-domain with chain BLAST (2681 domains)",
        "estimated_length": 242,
        "estimated_domains": 2681,
        "evidence_total": 10834,
        "chain_blast": 5000,
        "domain_blast": 5000,
        "hhsearch": 834,
        "tgroups": []
    },
    "8oqj_A": {
        "category": "single_domain_small",
        "description": "Small single domain (59 residues)",
        "estimated_length": 59,
        "estimated_domains": 1,
        "evidence_total": 80,
        "chain_blast": 40,
        "domain_blast": 40,
        "hhsearch": 0,
        "tgroups": []
    },
    "8oqh_A": {
        "category": "single_domain_small",
        "description": "Small single domain (58 residues)",
        "estimated_length": 58,
        "estimated_domains": 1,
        "evidence_total": 54,
        "chain_blast": 0,
        "domain_blast": 0,
        "hhsearch": 54,
        "tgroups": []
    },
    "8oyx_A": {
        "category": "single_domain_medium",
        "description": "Medium single domain (225 residues)",
        "estimated_length": 225,
        "estimated_domains": 1,
        "evidence_total": 99,
        "chain_blast": 0,
        "domain_blast": 0,
        "hhsearch": 99,
        "tgroups": []
    },
    "8oyw_A": {
        "category": "single_domain_medium",
        "description": "Medium single domain (179 residues)",
        "estimated_length": 179,
        "estimated_domains": 1,
        "evidence_total": 98,
        "chain_blast": 0,
        "domain_blast": 0,
        "hhsearch": 98,
        "tgroups": []
    },
    "8p49_A": {
        "category": "multi_domain_clear",
        "description": "Clear multi-domain (72 domains)",
        "estimated_length": 393,
        "estimated_domains": 72,
        "evidence_total": 264,
        "chain_blast": 0,
        "domain_blast": 0,
        "hhsearch": 264,
        "tgroups": []
    },
    "8p8o_H": {
        "category": "multi_domain_clear",
        "description": "Clear multi-domain (78 domains)",
        "estimated_length": 161,
        "estimated_domains": 78,
        "evidence_total": 183,
        "chain_blast": 0,
        "domain_blast": 40,
        "hhsearch": 143,
        "tgroups": []
    },
    "8oyu_A": {
        "category": "large_complex",
        "description": "Large protein (1237 residues, 917 domains)",
        "estimated_length": 1237,
        "estimated_domains": 917,
        "evidence_total": 5263,
        "chain_blast": 203,
        "domain_blast": 5000,
        "hhsearch": 60,
        "tgroups": []
    },
    "8oz3_B": {
        "category": "chain_blast_multi",
        "description": "Multi-domain with chain BLAST (2689 domains)",
        "estimated_length": 216,
        "estimated_domains": 2689,
        "evidence_total": 10822,
        "chain_blast": 5000,
        "domain_blast": 5000,
        "hhsearch": 822,
        "tgroups": []
    },
    "8p12_L": {
        "category": "chain_blast_multi",
        "description": "Multi-domain with chain BLAST (2828 domains)",
        "estimated_length": 238,
        "estimated_domains": 2828,
        "evidence_total": 10820,
        "chain_blast": 5000,
        "domain_blast": 5000,
        "hhsearch": 820,
        "tgroups": []
    },
    "8olg_A": {
        "category": "minimal_evidence",
        "description": "Minimal evidence (17 hits)",
        "estimated_length": 42,
        "estimated_domains": 1,
        "evidence_total": 17,
        "chain_blast": 6,
        "domain_blast": 11,
        "hhsearch": 0,
        "tgroups": []
    },
}

# Categories found in batch
BATCH_CATEGORIES = {
    "validated": ['8ovp_A'],
    "chain_blast_multi": ['8oni_L', '8p6i_L', '8p2e_B', '8oz3_B', '8p12_L'],
    "single_domain_small": ['8oqj_A', '8oqh_A'],
    "single_domain_medium": ['8oyx_A', '8oyw_A'],
    "multi_domain_clear": ['8p49_A', '8p8o_H'],
    "large_complex": ['8oyu_A'],
    "minimal_evidence": ['8olg_A'],
}